### ISSUE TITLE
Current version of Chocolately breaks cookbooks

### ISSUE THREAD

**Issue by ekrengel** [Nordstrom/chefdk_bootstrap#146] opened 2016-08-12 17:02 UTC
Latest version (0.10.0) of Chocolately require checksums not be empty. This is a breaking change for our cookbooks as we are not currently using checksums.

**Comment by donneler** [comment] 2016-08-12 17:21
Currently working on a work around to use empty checksums. Will need to work on a more secure solution afterwards.

**Comment by MarkGibbons** [comment] 2018-01-31 16:52
I don't see a problem here for us.  It seems like the fix should be upstream in the chef chocolatey package resource.  Will verify that the package are installed and then close this issue.

**Comment by ekrengel** [comment] 2019-04-29 19:12
@MarkGibbons can we close this issue or remove me as an assignee?

**Comment by MarkGibbons** [comment] 2019-04-29 19:29
Removed you.

**Comment by MarkGibbons** [comment] 2020-02-28 19:53
I can't reproduce this error any more.

**Closed by MarkGibbons** 2020-02-28 19:53 UTC
Labels: windows
